services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: reelsync
      POSTGRES_PASSWORD: reelsync
      POSTGRES_DB: reelsync

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/postgres-data
